### ISSUE TITLE
Rename saveData methods

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#12]
The name is fine, but maybe something like "saveResults" or a name that communicates that it's producing simulation result output files for other tools (for analysis, etc).

**Comment by stiber** [comment]
It's likely that this is already done; need to check with team.

**Comment by stiber** [comment]
This is already done; right?

**Comment by BodilessSleeper** [comment]
`[x@x Simulator] grep -R saveData
Core/Simulator.h:   void saveData() const; /// Writes simulation results to an output destination.
Core/Simulator.cpp:void Simulator::saveData() const {
Core/Simulator.cpp:   model_->saveData();
Core/Model.h:   /// Downstream from IModel saveData()
Core/Model.h:   virtual void saveData();
Core/BGDriver.cpp:   simulator.saveData();
Core/Model.cpp:void Model::saveData() {`
I'd say not done but I'm not sure if this is what you were talking about
