### ISSUE TITLE
ParameterManager should produce more specific error messages

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#124]
If the XPath doesn't exist, should indicate that, not just say it couldn't parse as type T.

**Comment by VivekGandhi54** [comment]
@jbrown725 Is this the same as the issue you fixed recently? Maybe #208 ?

**Comment by jbrown725** [comment]
Yeah, as of #212 if an xpath doesn't exist it will say `Failed loading simulation parameter for xpath <path>`.
