### ISSUE TITLE
Move ConnStatic parameters into config files

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#140]

**Comment by stiber** [comment]
This will likely relate to initial 911 simulation approach.

**Comment by torisalvatore** [comment]
Vivek going to update from Snigdha's branch. She has a good implementation of it.

**Comment by torisalvatore** [comment]
- [ ] Figure out and document ConnStatic parameters
- [ ] Create test config files
- [ ] Implement loadParameters for ConnStatic

**Comment by stiber** [comment]
@VivekGandhi54 is this done?

**Comment by VivekGandhi54** [comment]
Yeah, Snigdha's code was added in during the STDP merge.
