### ISSUE TITLE
Change NULL to nullptr

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#147]
There are still some places where this very minor cleanup is needed.

**Comment by BodilessSleeper** [comment]
Does this relate to all files (eg files in ThirdParty) and even comments (eg in Simulator/Core/Simulator.cpp)?
`/* PInput not in project yet
 if (pInput != NULL) {
     cout << "Initializing input." << endl;
     pInput->init();
 }
 */`

**Comment by stiber** [comment]
Needs to be fixed after subsequent merges of branches with large changes.
