### ISSUE TITLE
CPUSpikingModel shouldn't have any GPU stuff in it

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#150]
I think this just crept into this code, but it should just be in GPUSpikingModel.

https://github.com/UWB-Biocomputing/SummerOfBrain/blob/416b0c42beefdcc951e2b4ec441efafa0d6e529d/Simulator/Core/CPUSpikingModel.h#L65-L68

**Comment by torisalvatore** [comment]
Just notices of error. no implementation. 
`/// Copy GPU Synapse data to CPU. (Inheritance, no implem)
void CPUSpikingModel::copyGPUtoCPU() {
   LOG4CPLUS_WARN(fileLogger_, "ERROR: CPUSpikingModel::copyGPUtoCPU() was called." << endl);
   exit(EXIT_FAILURE);
}

/// Copy CPU Synapse data to GPU. (Inheritance, no implem, GPUModel has implem)
void CPUSpikingModel::copyCPUtoGPU() {
   LOG4CPLUS_WARN(fileLogger_, "ERROR: CPUSpikingModel::copyCPUtoGPU() was called." << endl);
   exit(EXIT_FAILURE);
}`
