### ISSUE TITLE
Update GitHub Pages to reflect Graphitti branding.

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#160]

**Comment by stiber** [comment]
* Current top-level Graphitti page should be (with light edits) the lab repo landing page, linking to the sub-repo landing pages.
* Can still point to old BG repo, since that still works and is the only multi-GPU simulator.

**Comment by jbrown725** [comment]
Working on this issue, but not sure how to assign myself to it. Maybe I lack a permission, or maybe I'm just missing something.
