### ISSUE TITLE
Separate names for each executable

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#172]
**CPU:** cgraphitti
**GPU:** ggraphitti

**Comment by BodilessSleeper** [comment]
So basically if we compile with CUDA_ENABLED in CMakeList.txt it should only compile ggraphitti otherwise we should only compile cgraphitti, right?

**Comment by BodilessSleeper** [comment]
If I understood you correctly then the solution is provided in the above PR

**Comment by BodilessSleeper** [comment]
@stiber you could close the issue now
