### ISSUE TITLE
Document synapse spike delay queuing and fix it

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#181]
Right now, I believe we have a bit index that indicates the front of the delay queue and we increment that, mod the queue length. Instead, it seems like the front of the queue should just be bit 0 and we should:

- Shift the queue instead of incrementing a front index value.
- Always insert new spikes at the same bit location, determined by the delay for that synapse.

This seems like it will reduce the state information associated with each synapse with no loss in performance. _However_, it is important to carefully document how it works right now, to make sure that this seeming improvement isn't actually a misunderstanding of subtle reasons why the current design isn't a slick idea.

**Comment by stiber** [comment]
Basically the same as #133

**Comment by PoojaPal2021** [comment]
It is fixed by PR #315
