### ISSUE TITLE
Remove Probled neuron list from the simulator

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#182]
So, what do the HDF5 recorder classes get when they ask the Layout for the list of probed neurons? This seems like potentially a big problem.

- Certainly, the neuron layout classes should load the probed neuron list file name from the parameter manager and then load that neuron list, so this part definitely needs to be restored to the simulator.
- Then, the question above should be addressed with appropriate error checking.

**Comment by PoojaPal2021** [comment]
Plan is to eliminate probled neuron feature from the simulator.
