### ISSUE TITLE
fix zone hardcoding

### ISSUE THREAD

**Issue by torisalvatore** [UWB-Biocomputing/Graphitti#186]
`zone() ` method in layout911 is hardcoded. resolve with proper code before closing out math of MVP

**Comment by VivekGandhi54** [comment]
Add zone dimensions in Layout parameters. Perhaps assign a zone to each vertex and maintain a zoneMap? This would allow us to have non-rectangular uniform zones too.

**Comment by jardiamj** [comment]
This will no longer be needed once the ability to load graphML files is completed.

**Comment by jardiamj** [comment]
Closing this one because is no longer needed.
