### ISSUE TITLE
Unnecessary overridden methods in Edge class hierarchy

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#198]
I believe there are overrides in subclasses (for example, `AllNeuroEdges::AllNeuroEdges(const int numVertices, const int maxEdges)`) that are identical to the superclass method and therefore don't need to be there.

**Comment by stiber** [comment]
Moreover, there are methods that are overridden that aren't labeled that way (such as `AllSpikingSynapses::resetEdge()`).

**Comment by stiber** [comment]
Maybe `AllSTDPSynapses::initSpikeQueue()`

**Comment by stiber** [comment]
Maybe `AllSTDPSynapses::isSpikeQueuePost()` and `AllSTDPSynapses::postSpikeHit()`.

**Comment by VivekGandhi54** [comment]
I think that `AllSTDPSynapses::initSpikeQueue()` does something different from `AllSpikingSynapses::initSpikeQueue()`, it accesses different arrays.

I also don't think that `AllSTDPSynapses::isSpikeQueuePost()` and `AllSTDPSynapses::postSpikeHit()` do similar things. The process of fetching references to specific array members makes the code look similar.
