### ISSUE TITLE
GPU build encounters linking error

### ISSUE THREAD

**Issue by VivekGandhi54** [UWB-Biocomputing/Graphitti#201]
`AllSTDPSynapses::synapticWeightModification`  is within a `!defined(USE_GPU)` block in AllSTDPSynapses.cpp.
I'm unsure about whether its declaration should be in such a block too, or if the definition should be outside this block.

**Comment by stiber** [comment]
Yes, the GPU build is currently a mess. Let's get the CPU version completely working and validated first, and then we will tackle the GPU version step by step.
