### ISSUE TITLE
ParameterManager error messages produced during at least some simulator runs

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#208]
We get the following error messages when running `test-tiny.xml` and `test-small.xml`. Might be true for other config files:

```
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
Parsed parameter could not be parsed as a float. Value: 
```

**Comment by stiber** [comment]
I think this is a case where the config files need to be updated, or where they were typoed during an untested update.

**Comment by VivekGandhi54** [comment]
Snigdha's code implemented `AllSpikingSynapses::loadParameters`, which asks for these floats. None of them are defined in any of the old config files:

```
//tau/ii/text()
//tau/ie/text()
//tau/ei/text()
//tau/ee/text()
//delay/ii/text()
//delay/ie/text()
//delay/ei/text()
//delay/ee/text()
```

**Comment by stiber** [comment]
But wouldn't they only be relevant if the synapse/edge class is "AllSTDPSynapses"?

Otherwise, that class's `loadParameters()` won't get called and ask for them.

**Comment by VivekGandhi54** [comment]
`test-medium.xml`, `test-small.xml`, and `test-tiny.xml` all use `AllDSSynapses`, which derives from `AllSpikingSynapses`, where it's implemented.
`AllDSSynapses` doesn't overload that function.

**Comment by stiber** [comment]
Oh are you saying that the STDP parameters are being loaded from the superclass code, not from `AllSTDPSynapses` override? That would be problematic. The top-level class should establish a binding to whichever implementation of `loadParameters()` a class actually uses.

It certainly is the case that we haven't implemented parameter loading for the other synapse classes; they're all hard coded. So, we have three things to do here (assuming the above is true):

- [ ] Move STDP synapse parameter loading to that class.
- [ ] Add parameter loading for all other synapse classes.
- [ ] Update all config files that need to be updated.

@jbrown725, this could be a good place to start digging more deeply into the code, where you're ready. It's relatively contained (i.e., doesn't require knowing everything first).

**Comment by jbrown725** [comment]
I'll look at these classes and we can talk about it at our meeting tomorrow. I agree, a defined problem in a small ecosystem of code is a good way for me to start getting comfortable.

**Comment by stiber** [comment]
The main problem seems to just be that we now load spiking synapse parameters, but those config files don't provide them. So, ignore my previous comment (I will see if I can hide it). Instead:

- [ ] Improve the `ParameterManager` error reporting.
- [ ] Update config files to specify parameter values (ask @stiber for values to use, if needed).
