### ISSUE TITLE
Test config files with static connections do not run

### ISSUE THREAD

**Issue by jbrown725** [UWB-Biocomputing/Graphitti#213]
Test config files with the connection class "ConnStatic" do not run unless one or both of the `threshConnsRadius` or `connsPerNeuron` parameters are set to 0. If both are nonzero, the program either segmentation faults at line 256 of AllSpikingSynapses or outputs an error  to edges.txt and quits at line 262. The error it outputs looks like `Delay Queue Error 0 idx22 iSync 0`, with the number after idx sometimes being different.

This affects the following files:

- test-medium-connected-stdp 
- test-medium-stdp 
- test-small-connected-stdp 
- test-tiny-stdp
- test-tiny-xml-stdp

**Comment by VivekGandhi54** [comment]
I think there's an error in the bitwise queue initialization.
`AllSpikingSynapses::isSpikeQueue` near line 236:
`delayQueue &= ~(0x1 << delayIdx);`

If `delayQueue` is initialized to 0, then this will do nothing.

Then, in `AllSpikingSynapses::preSpikeHit` near line 260:
`(delayQueue & (0x1 << idx)) == 0` will always be true.
