### ISSUE TITLE
AllSpikingSynapses::preSpikeHit causes an assertion error with test-tiny.xml

### ISSUE THREAD

**Issue by VivekGandhi54** [UWB-Biocomputing/Graphitti#222]
Line 260 evaluates to true _sometimes_
`if((delayQueue & (0x1 << idx)) != 0)`

We changed this last week.
`test-tiny.xml` provides a constant rng seed, so I'm not sure why it doesn't break (or not break) with every single run.

**Comment by stiber** [comment]
Well, the whole reason to have a if/then is for the test to be true sometimes, right? :^)

Regarding the seed in the config files, I'm not sure it's used in the simulator. Note that there are two RNGs -- one to initialize parameters and one to generate simulator noise. It would be good to seed them from the config files, but that seeding may be hard-coded. _Essential_ will be for us to be able to seed them identically in different runs, so we can do regression (and other) testing.

**Comment by VivekGandhi54** [comment]
Oh yeah, RNG seeding is issue #21. I'll work on that also.

**Comment by VivekGandhi54** [comment]
`AllEdges::createEdgeIndexMap()` was writing on dirty data. Based on the implementation, I had figured that there was no need to initialize the array. Turns out that `createEdgeIndexMap()` had a bug affecting the case when the number of edges is 0, like in `test-tiny.xml`.

**Comment by VivekGandhi54** [comment]
`EdgeIndexMap` constructor doesn't initialize its internal arrays. Initializing it in the constructor may not be ideal as you'd still be writing on dirty data after the first time.
