### ISSUE TITLE
Have graphitti output its associated commit ID

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#226]
The basic idea here is to be able to run, say, `graphitti -v` and have graphitti output the commit ID from which it was built and quit (not running a simulation). An off-the-cuff idea how this might be accomplished would be to have CMake run `git` to get the repo's commit ID, then have it add a `-DCOMMIT=<that ID>` to the g++ command line (or the `CFLAGS`) in the Makefile it generates. That macro definition could be used in the code to accomplish this.

This is something that will be desirable for Workbench interoperability.

**Comment by VivekGandhi54** [comment]
Accomplished this using a cmake-generated `config.h` file.
Unsure about the specific message it should output, or the length of the commit ID (short 7 hex chars vs full 40 hex chars).

**Comment by stiber** [comment]
After some thought, let's output the full commit ID (40 digits). Workbench can always deal with the UI issue to substitute something other than typing a commit ID in.
