### ISSUE TITLE
test-tiny fails sometimes

### ISSUE THREAD

**Issue by jbrown725** [UWB-Biocomputing/Graphitti#230]
Something has changed recently that makes test-tiny behave inconsistently. Sometimes it completes successfully, sometimes it segmentation faults, and sometimes it gives this error:
```
.../AllSpikingSynapses.cpp:263: virtual void AllSpikingSynapses::preSpikeHit(uint32_t): Assertion `false' failed.
```
This doesn't seem to happen with any of the other test files. Likely related to 034298ca07f8adfe162ab6a24a9757446f5727af.

**Comment by VivekGandhi54** [comment]
Same as #222
