### ISSUE TITLE
HDF5Recorder::compileHistories causes an assertion error

### ISSUE THREAD

**Issue by jbrown725** [UWB-Biocomputing/Graphitti#234]
HDF5 output works fine on `test-tiny-hdf5.xml`, but when I made a version of `test-small` that uses the `HDF5GrowthRecorder`, it fails an assertion at line 268 of `HDF5Recorder`:
` assert(idx1 >= 0 && idx1 < simulator.getEpochDuration());`

Some notes:
- The problem is that `idx1` is >= `simulator.getEpochDuration()` on a simulation with more than 1 epoch. 
- This assertion is to prevent `burstinessHist_[idx1]++` on the next line from writing outside of bounds, since `burstinessHist_` has a length of `simulator.getEpochDuration()`.
  - Two lines down, `spikesHistory_[idx2]++` is similarly at risk of writing out of bounds, but doesn't have its own assertion.
- Removing this assertion predictably causes a segmentation fault.
- Removing the assertion and arbitrarily making both `burstinessHist_` and `spikesHistory_` twice as long allows `test-small` to complete and write to a .h5 file successfully.

So the solution would be to either initialize these two arrays to a larger, hopefully non-arbitrary value OR figure out why `idx1` and `idx2` are being calculated as values too large for their arrays to hold them. If `idx1` and `idx2` are being calculated correctly, then the array needs to be bigger to fit them.

Also:
- This assertion does not exist in `XMLRecorder`
-  `burtsinessHist_` and `spikesHistory_` are of type `VectorMatrix` in `XMLRecorder`, so dynamic resizing means writing out of bounds is not an issue.

Another solution might be to change these two arrays to both be a `VectorMatrix` in `HDF5Recorder`, but that might not be possible due to the H5 write method wanting an array as an output buffer.

**Comment by VivekGandhi54** [comment]
Seems like the hdf5 recorder doesn't account for simulations with multiple epochs.
These changes should fix it:

`Hdf5Recorder.cpp`, lines 172:175:
```
// allocate and initialize data memories
burstinessHist_ = new int[static_cast<int>(Simulator::getInstance().getEpochDuration() * Simulator::getInstance().getNumEpochs())];
spikesHistory_ = new int[static_cast<int>(Simulator::getInstance().getEpochDuration() * Simulator::getInstance().getNumEpochs() * 100)];
memset(burstinessHist_, 0, static_cast<int>(Simulator::getInstance().getEpochDuration() * Simulator::getInstance().getNumEpochs() * sizeof(int)));
memset(spikesHistory_, 0, static_cast<int>(Simulator::getInstance().getEpochDuration() * Simulator::getInstance().getNumEpochs() * 100 * sizeof(int)));
```

Line 268:
```
assert(idx1 >= 0 && idx1 < (simulator.getEpochDuration() * Simulator::getInstance().getNumEpochs()));
```

**Comment by stiber** [comment]
@VivekGandhi54 has a brute-force solution, but I don't think it's necessary to go that far. The original code from BrainGrid did work, and the only issue is likely that we're missing something from that repo. For one thing, we're switching to incremental writing of HDF5 files (rescuing some code from later commits of BrainGrid). What should be happening here is that these indices get reset after the end-of-epoch action of the recorder class finishes dumping the buffered information into the HDF5 data structures. So, something got lost along the way.

We actually should lose the burstiness history stuff; that is left over from an age when we didn't capture all of the network activity (too slow and files too big at that point in time). Now, we save all such activity and can calculate stuff like that after the simulation completes.

**Comment by VivekGandhi54** [comment]
Oops. I figured that it wasn't being written to file until the end of the simulation with `saveSimData`.
