### ISSUE TITLE
Validate GPU output of Graphitti vs BrainGrid

### ISSUE THREAD

**Issue by jbrown725** [UWB-Biocomputing/Graphitti#238]
Run simulations on the GPU and make sure the outputs are the same. Plan to run:

- [x] test-small
- [x] test-small-connected
- [ ] test-medium
- [ ] test-medium-connected
- [x] test-large-short
- [x] test-large-short-connected

**Comment by jbrown725** [comment]
@stiber The small and large tests are outputting identical results. All four of those tests are 2 epochs. The two medium tests are 20 epochs, and they start showing differences in spikes and radii after connections start forming. For test-medium this begins on epoch 14, and for test-medium-connected it starts on epoch 3. 

The differences in the values and frequencies are very small at first, but they do noticeably increase a bit as the simulation goes. It would probably be more notable with a much longer simulation.

I guess the question is are these expected differences due to the less predictable nature of GPU execution, or is there something we should track down that could fix it like with the CPU testing?

**Comment by stiber** [comment]
I think we've talked about this well enough in person, but let me know if that's not the case.
