### ISSUE TITLE
Switch from dynamic arrays to <valarray> or <vector>

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#24]
There are advantages to wrapping these in objects; we need to ensure that nothing gets reallocated when we don't want that to happen. For either classes, we can always get a primitive pointer to the underlying array representation, so there is no worry about performance or copying back and forth to the GPU.

**Comment by stiber** [comment]
For the record, [here](https://hackernoon.com/c-investigation-arrays-vs-vectors-e9ba864468b6) is an interesting page that compares primitive array and vector access performance with different levels of optimization in the compilation.

This probably requires us to address issue #159, so that we can compile with optimization on.

**Comment by stiber** [comment]
Or maybe valarrays? Probably should do some performance tests. But we don't need automatic resizing, just the ability to set the array size at run time, so it seems like valarrays may be what we want. It's actually rather embarrassing that valarrays have apparently been around since C++98 and yet I've never heard of them.

**Comment by stiber** [comment]
[Here](https://stackoverflow.com/questions/1602451/c-valarray-vs-vector) is a decent discussion item on `valarray`s. And, of course, our own comparison of [array performance](https://uwb-biocomputing.github.io/Graphitti/InternalTesting/).

Note that `valarray` has operations that have some similarity to Matlab. This is because of FORTRAN, which of course predates all this and of which all of the designers of these tools/languages would have been very familiar with. And this sort of stuff also appears in Python, via things like `numpy`. So, there is a syntactic commonality that can produce code that is similar in all of these languages.

One additional question we might ask is if we are doing array/vector operations that could be improved by the `valarray` interface (or its associated slice classes). However, this is somewhat unlikely, as we mostly operate on elements of our arrays separately, in an "embarrassingly parallel" manner.

**Comment by VivekGandhi54** [comment]
I think that we can use `valarray` slicing to efficiently implement vertex probing. We could just pick out the exact points of data that we care about. I think it would also work pretty well with the Recorder class redesign (#240) and the current format of the probed lists.
