### ISSUE TITLE
Consolidate unnecessary extra CMakeLists.txt files into the top level CMakeLists.txt file.

### ISSUE THREAD

**Issue by msorvik** [UWB-Biocomputing/Graphitti#282]

**Comment by VivekGandhi54** [comment]
FYI, the CMakeLists.txt within the RNG folder explicitly defines it as a shared library. This was a fix to an older issue where the simulator would come across a linking error when running a GPU sim. Just want to make sure that it doesn't break again.

**Comment by msorvik** [comment]
Ah yes I did run across that today. I was wondering why that's the case but didn't find an answer. I did see that it causes unexpected behavior if changed though so I left it that way

Interesting that some of the libraries containing CUDA files need to be declared as STATIC to avoid linker issues, and this one needs to be declared as SHARED to avoid linker issues.

Thanks for the info

**Comment by msorvik** [comment]
Actually after more testing, it works fine as STATIC when CUDA_SEPERABLE_COMPILATION is set to ON for that library, so I changed it to that. This will be good because it's consistent with how the other CUDA containing libraries are set up now also.
