### ISSUE TITLE
Document top-level program flow

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#305]
The whiteboard image below is an old summary of the top-level simulator execution sequence. We need to produce an up-to-date version of this, possibly as a UML sequence diagram but maybe not. We also need to incorporate into this information regarding when each kind of class gets instantiated, when each kind of class reads its parameters, and when each kind of class initializes itself.

![Top Level Sequence](https://user-images.githubusercontent.com/1878411/151039073-6c2d9e11-fa74-41c3-b221-9c9363bad631.png)

**Comment by valenotary** [comment]
I was literally working on something like this yesterday, coincidentally! I was planning on trying to demonstrate the program flow of graphitti in a sequence diagram - it may take me awhile, but I'll use that whiteboard info, @VivekGandhi54 's knowledge, and the source code to guide the diagram.

**Comment by valenotary** [comment]
Update: I just finished a first pass through the source code to generate this sequence diagram; not sure if we'd like to go deeper in some parts, or if I should specifically discern between which Model (e.g. CPU/GPU) the code path is executing on, and it's definitely not the easiest thing to look at... but aside from all of that, here it is. 
![Graphitti General Program Flow](https://user-images.githubusercontent.com/32428785/151503762-b33c8de1-0a8c-48ac-8ef8-3188567cb2b8.png)
[Here is the sequence diagram source](https://github.com/UWB-Biocomputing/Graphitti/files/7956568/Graphitti.General.Program.Flow.txt), that can be uploaded to https://sequencediagram.org/ to be edited.

**Comment by jardiamj** [comment]
I was wrong about git natively supporting plantUML, it doesn't. Regardless, I turned Tony's diagram into plantUML, added a few things, and split it in 3: 
- A top level program flow.
- Simulator::instantiateSimulatorObjects, and
- Simulator::simulate

Another diagram for the Simulator::setup might also be appropriate.

**Top Level Sequence Diagram:**
![graphitti sequence diagram](https://user-images.githubusercontent.com/1088732/152675405-dc733f18-13fb-4c34-988f-46603d8ad5d7.png)

**Simulator::instantiateSimulatorObjects**
![Instantiate Simulator Objects](https://user-images.githubusercontent.com/1088732/152674950-88563b62-7091-4718-8958-e642245f72f5.png)

Simulator::simulate
![Simulator Simulate](https://user-images.githubusercontent.com/1088732/152674958-7db0d51e-d211-4221-9750-681f12d58187.png)

**Comment by rashwini21** [comment]
Thank you for this. Sequence Diagram is works like a charm. Here is working " model_->advance " statement from "Simulator.simulate" and its respective comparison for Growth and STDP models. 
![AdvanceFunctionSequenceDiagram](https://user-images.githubusercontent.com/92547460/159356659-c75f73bd-42d0-4081-aa8e-3febd082df45.png)

**Comment by stiber** [comment]
These are looking good. Conor McIntosh @NewBobCon will start off his undergrad capstone by helping finalize and integrate this into our documentation, so he can take some of the load of detailed tweaking and automation of updating this. This will also help him learn GitHub automation, which he'll bring into an effort to automate code quality testing.
