### ISSUE TITLE
Write up coding and documentation standards and link into GH pages

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#32]
See issue #31 for some examples. Will include picayune details. Big things would include:

- Avoid raw pointers whenever possible, instead either avoiding pointers altogether (using reference, etc.) or using smart pointers.
- Guard against problems by using things like marking operations `= delete`.
- Rather than dynamically allocated arrays, we will use `vector`s, which we will set to a particular size. We can always access the array within the `vector` to do numerical operations, loops, etc.
- Many more things. I believe that Google has a public style guide, which we can liberally steal from.

**Comment by stiber** [comment]
@torisalvatore this is written, right? Just needs to be linked in?

**Comment by stiber** [comment]
At least part of this is done under https://github.com/UWB-Biocomputing/Graphitti/tree/master/docs/_Info

**Comment by jardiamj** [comment]
I believe that this was addressed by @KamathScience  in PR #422. We might be able to close this one :smile:

**Comment by stiber** [comment]
Yup.
