### ISSUE TITLE
Extend EventBuffer class to work with GPU

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#339]
Note: `AllIFNeurons:: allocDeviceStruct()` does allocation of all of the neuron data structures on the GPU.

Class needs at least one additional methods: 

First, we definitely need something like `EventBuffer::copyFromGPU()`. This should implement the current functionality of much of `AllSpikingNeurons::copyDeviceSpikeCountsToHost()` and the body of the loop in `AllSpikingNeurons::copyDeviceSpikeHistoryToHost()`. I suggest that these two methods be merged into one (that calls `EventBuffer::copyFromGPU()`) within the `AllSpikingNeurons` class and the place that calls these two methods be changed to just call that one method. This will minimize changes to the existing code base (and require no changes to the GPU code), and it's really not possible at this point in time to further encapsulate things because all GPU side data is stored within arrays pointed to by the `allVerticesDevice` struct.

Then we need to think about `AllSpikingNeurons::clearDeviceSpikeCounts()`. At first glance it seems we need to have conditional compilation (for GPU) statements in `EventBuffer::clear()` that will call this method. The problem here is that the `EventBuffer` object doesn't know the address of the corresponding data structure on the GPU. Instead, we need to look at where the `EventBuffer` objects are cleared and where `AllSpikingNeurons::clearDeviceSpikeCounts()` is called.

 I believe that we haven't yet pushed `EventBuffer` into the IZH neuron model; perhaps we need to pull that code temporarily out of the code base and roll it into an undergrad project to mirror the changes to the spiking/IF/LIF classes.

**Comment by stiber** [comment]
Actually, I'm not sure the body of the loop can be put inside the `EventBuffer` method. That loop is actually reading the equivalent of one `EventBuffer` object for each iteration. Also, it seems that there is also a need to implement a `copyToGPU()` method. Also, from conversation with @PoojaPal2021, there is a lot that I didn't take into account in my initial thoughts. This needs to be worked through more carefully.

**Comment by stiber** [comment]
Maybe we need a class hierarchy, with a top level `GPUEnabledVector`, that is a subclass of `vector`, and that adds public "copy to/from device" methods.

![IMG_1246](https://user-images.githubusercontent.com/1878411/190872560-5c6ddfed-f8ea-46b1-a012-d517049668da.jpeg)

**Comment by PoojaPal2021** [comment]
some of the aspects if this issue are handled by the #354 and #365. 
Generic Recorder structure( super class of EB, as shown in the picture above) is going to be implemented as a part Recorder reengineering
