### ISSUE TITLE
Gihub action for manually deploying the documentation to gh-pages wipes out our Doxygen documentation

### ISSUE THREAD

**Issue by jardiamj** [UWB-Biocomputing/Graphitti#343]
The GitHub action for manually deploying the documentation to the gh-pages branch wipes out the generated HTML Doxygen documentation. The reason is that there are we are using `force_orphan` to have a clean, no history branch with only our latest documentation; but because the Doxygen documentation files are generated they don't exist in our Main branch so when we copy over the content of `docs` into the `gh-pages` we are overwriting it with a `docs` directory that doesn't have any Doxygen documentation.

We have two options to fix this:
- Modify the action so that it also generates the Doxygen documentation.
- Remove the `force_orphan: true` statement so that it will show as a commit with history: I believe this should leave files in gh-pages even if they don't exist in our master branch, but I am not sure.

**Comment by NewBobCon** [comment]
I wonder if we take away the `force_orphan: true` would the monthly script come in and wipe out the commit history for us? The point of this manual script was to not have to regenerate Doxygen files all the time. @stiber do you have a preference for what fix should be implemented? I would think removing `force_orphan: true` would be the simplest.

**Comment by NewBobCon** [comment]
Even with getting rid of the `force_orphan: true`, the HTML folder in the Doxygen directory still gets wiped out by the manual script. I've pivoted to rebuilding the Doxygen files within the manual publish action. Which, from my testing, seems to work the way we want it to. There is no commit history associated with the gh-pages branch and all documentation/doxygen files are present.
