### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by crayzeerr** [UWB-Biocomputing/Graphitti#353]
1.2.2: "Download a release" hyperlink does nothing as we are already where the link is supposed to direct you to
1.2.2: "Fork and Clone Graphitti" doesn't take you to a different page 
1.2.2.1: Says there are no releases, but on BrainGrid GitHub page there are 5 releases 
1.2.3: Where is CMakeLists.txt located? 
1.3.2: Where do I open my Linux terminal to call the screen command? 
3.2: Isn't int main supposed to return a 0 at the end? (https://uwb-biocomputing.github.io/Graphitti/Testing/CastingTest/CastingTest.cpp)

**Comment by stiber** [comment]
I think these can be a set of small things that you could work on to familiarize yourself with our software development processes. Read our contributing guide and then touch bases with me on this.
