### ISSUE TITLE
Stabilize current EventBuffer implementation

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#354]
We are implementing this class first in a way that doesn't require any modification of GPU code. Instead, we are writing CPU-side code to copy to-from the GPU side that translates between the CPU and GPU data structure reorganizations.

**Comment by PoojaPal2021** [comment]
The event buffer data structure to capture neuron spike has been extended to GPU side. We are only writing CPU side code to copy to-from the GPU side that translates between the CPU and GPU data structure reorganization
