### ISSUE TITLE
Modify the GPU code to use the CPU EventBuffer organization

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#355]
While this means throwing away the translation on copy code previously implemented in #354, this allows us to separately validate code for CPU and for GPU, and does not require detailed understanding of CUDA to accomplish that earlier task.

**Comment by PoojaPal2021** [comment]
completed the following things.
1. multiple methods were present to accomplish the copy to or from Device. Clubbed them into one.
2. completed the the renaming of copy methods to to avoid confusion
