### ISSUE TITLE
Change top-level vertex device (pure virtual) copying methods

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#365]
Change to `copyToDevice()` and `copyFromDevice()`.

Note that, for subclasses, at each level in the hierarchy, should copy the corresponding *new* elements of the device properties `struct`. So, it should call the superclass copy method first.

Also, all of these methods should take a single argument that is a device address. Right now, we're using `void *`; let's use a `typedef` to define `DeviceAddress` as the same thing as `void *` temporarily.

https://github.com/UWB-Biocomputing/Graphitti/blob/c21552bd8ae06ac828cce9ba711bba413935803d/Simulator/Vertices/AllVertices.h#L94-L102

**Comment by PoojaPal2021** [comment]
I have completed the following this.
1. Renaming `copyNeuronHostToDevice()` to `copyToDevice()`
2. Renaming  `copyNeuronDeviceToHost()` to `copyFromDevice()`
3.  This change has been cascaded from top level neuron class to all its sub classes
