### ISSUE TITLE
Rename Testing subfolder 'Core' to 'UnitTesting'

### ISSUE THREAD

**Issue by KamathScience** [UWB-Biocomputing/Graphitti#368]
#### Description
The subfolder `Core` under Testing has unit tests from all the components of the simulator, not just the Core. Hence the name should be replaced with `UnitTesting`. This name will also be consistent with the names of other sub-folders in Testing like `RegressionTesting`. Finally, it is important to reflect this change in CMakeLists.txt and any other file that uses the unit tests.

#### Files
- [Graphitti](https://github.com/UWB-Biocomputing/Graphitti)/Testing/
- [Graphitti](https://github.com/UWB-Biocomputing/Graphitti)/CMakeLists.txt

#### Tasks
- Change the name of the sub-folder 'Core' to 'UnitTesting'.
- In theCMAKEList.txt, update the path of the unit tests.
- Check if any other files need to be updated.
- Test the changes.

**Comment by stiber** [comment]
Also add at least a `TestOutput` subdirectory, and entries in `.gitignore` to not track `.xml` and `.h5` files there.
