### ISSUE TITLE
Simulator class contains pointers that are never used nor initialized.

### ISSUE THREAD

**Issue by jardiamj** [UWB-Biocomputing/Graphitti#372]
The Simulator class contains the following pointers that are never used nor initialized:
- `vertexType *rgNeuronTypeMap_`, and
- `bool *rgEndogenouslyActiveNeuronMap_`

There are getters for these but they are not called anywhere. They should be removed if not needed.

Besides, the class has a pointer (`pSummationMap_`) to the vertices `summationMap_`. The getter for this pointer is called in two places:
- HostSInputRegular.cpp, and
- SInputPoisson.cpp

If we really need to get the vertices `summationMap_` from the Simulator class, we could get it from `model_->getLayout()->getVertices()->summationMap_` rather than having the same pointer in two places. It also presents the assumption that all models have a summation map.

**Comment by stiber** [comment]
This connects to one of the remaining "most confusing" parts of the simulator.
