### ISSUE TITLE
Need to edit comments in EventBuffer to mark the end of the Recorder interface

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#395]
using Doxygen `///@}`, I believe.

https://github.com/UWB-Biocomputing/Graphitti/blob/84d9f6ee28264e2a50ba211ec5efd2a30be6b7d2/Simulator/Vertices/EventBuffer.h#L66

**Comment by xiangli6** [comment]
PR#492 is deleted because it contains unwanted commits.
