### ISSUE TITLE
Empty space in GoodOutput test-small-out.xml and test-small-connected-long-out.xml cause regression tests to fail.

### ISSUE THREAD

**Issue by jardiamj** [UWB-Biocomputing/Graphitti#418]
The Regression tests for test-small and test-small-connected-long fail because there are empty spaces in the following lines:

Testing/RegressionTesting/GoodOutput/test-small-out.xml: Line 14
Testing/RegressionTesting/GoodOutput/test-small-connected-long-out.xml: Line 30

https://github.com/UWB-Biocomputing/Graphitti/blob/21a4b30fa671b5b5418cb9bafd7cdc0c60e9b87d/Testing/RegressionTesting/GoodOutput/test-small-out.xml#L14

https://github.com/UWB-Biocomputing/Graphitti/blob/21a4b30fa671b5b5418cb9bafd7cdc0c60e9b87d/Testing/RegressionTesting/GoodOutput/test-small-connected-long-out.xml#L30

**Comment by xiangli6** [comment]
Hi Jardi, I Ieave that an empty space between "ratesHistory" and "spikesHistory" on purpose. I observed each GoodOutput/ output file in the original master branch and found there is an empty space between "ratesHistory" and "burstinessHist" so I though if I delete the "burstinessHist" value, there should be an empty space there.
https://github.com/UWB-Biocomputing/Graphitti/blob/cae362b2012692d8152aa932a4643e206271f7dc/Testing/RegressionTesting/GoodOutput/test-small-out.xml#L14

**Comment by xiangli6** [comment]
Thanks. I saw that empty space in the empty line. Do I need to update the file and push it to GitHub?

**Comment by xiangli6** [comment]
These two regression testing files were updated.
