### ISSUE TITLE
Remove either '#ifdef' directives or '#pragma once'

### ISSUE THREAD

**Issue by KamathScience** [UWB-Biocomputing/Graphitti#427]
A few files like `Global.h` have both `#pragma once` and `#ifdef` directives defined in the same file. Both these directives are intended to prevent multiple inclusions of header files. As per C++ standard `#pragma once` is usually sufficient to prevent multiple inclusions by itself. However, we must aim to clean these and keep which serves best based on the use case.

**Comment by stiber** [comment]
Note that this requires a thorough audit of all of our `.h` files so that they are all fixed.
