### ISSUE TITLE
Change array performance testing doc to a table

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#454]
https://github.com/UWB-Biocomputing/Graphitti/blob/87ca18f1c0a09b3a92ce0c35f4303470ad96a130/docs/Testing/ArrayPerformance/ArrayPerformance.md?plain=1#L19

**Comment by coderSuren** [comment]
Hi @stiber, I would like to work on this issue

**Comment by stiber** [comment]
> Hi @stiber, I would like to work on this issue

Thanks for contacting us! If you think you can follow what's written there, then feel free to do so. Please fork the repo and make the change off of the master branch. See our contributing guide for more information.
