### ISSUE TITLE
Look into PyNN

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#455]
Is this something interesting that we can support? Main website is at https://ebrains.eu/service/pynn/. Basic description:

> Computational neuroscientists have developed a diversity of software platforms for simulating neural network models at different scales. However, each simulator has its own programming or configuration language, leading to considerable difficulty in porting models from one simulator to another. A common programming interface to multiple simulators would help to reduce or eliminate the problems of simulator diversity while retaining the benefits. PyNN is such an interface, making it possible to write a simulation script once, using the Python programming language, and run it without modification on any supported simulator (currently including NEURON, NEST, Brian, and the SpiNNaker and BrainScaleS neuromorphic hardware systems).

**Comment by silvercube227** [comment]
added presentation to google drive
