### ISSUE TITLE
Enhancing build efficiency with the -j option in the make command

### ISSUE THREAD

**Issue by KamathScience** [UWB-Biocomputing/Graphitti#460]
#### Description
The `-j` option in the `make` command allows users to control the number of simultaneous jobs executed by `make`, thereby improving the build process efficiency of Graphitti by leveraging multiple processors or cores on the system.

#### Usage
To utilize the `-j` option, append it to the `make` command. If the specific number of jobs is not mentioned, `make` will utilize all available cores on the system.
`make -j`

#### Task
01. Update the Graphitti Documentation
02. Add `-j` to the GitHub Actions workflow file; for faster testing

**Comment by stiber** [comment]
Also, would be good to do some before/after performance measurement on raiju and otachi.

**Comment by Andrzej-Dawiec** [comment]
Just finished, see pull request but results are as follows on Raiju machine:

Google unit tests: around 2ms faster
CPU Test: Minimal Difference
GPU Test: Around 3 seconds faster

**Comment by Andrzej-Dawiec** [comment]
Will test on otachi machine as well, so far Raiju is around 3 seconds faster on GPU.

**Comment by Andrzej-Dawiec** [comment]
Good afternoon @stiber I have measured changes in building performance on the lab machines, with my noticing being around ~half a second faster with the -j option enabled on compilation.
