### ISSUE TITLE
Produce list of third-party tools and libraries

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#47]
Including versions known to work for us.

Also, determine what needs to be updated/installed on CSS research machines.

**Comment by torisalvatore** [comment]
Done 
https://github.com/UWB-Biocomputing/Graphitti/blob/416b0c42beefdcc951e2b4ec441efafa0d6e529d/docs/BGDocs/02a_installRequirements.md

**Comment by torisalvatore** [comment]
refer to issue #47 for current updates. closing this.
