### ISSUE TITLE
Write up GitFlow documentation; add to or link to contributing guide

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#473]
And draw up our version of the diagram, with our own modifications regarding merging the development branch, using PlantUML.

**Comment by Andrzej-Dawiec** [comment]
I will add onto the contributing guide.

**Comment by stiber** [comment]
Some notes:

- [GitFlow article](https://datasift.github.io/gitflow/IntroducingGitFlow.html)
- Need to update CONTRIBUTING.md
- Should redraw diagrams, rather than copy them, so look into #501
