### ISSUE TITLE
Add an additional subclass/concrete class to the Recordable and make it working with the XmlRecorder

### ISSUE THREAD

**Issue by xiangli6** [UWB-Biocomputing/Graphitti#504]
The objective of this issue is to add a new subclass/concrete class to the recordable framework so that the XmlRecorder can work with it effectively.

**Comment by xiangli6** [comment]
Our initial design involves each Recorder class containing a variable table. However, issue 240 highlights that each variable has a temporal resolution, with some requiring updates every time step, while others may update less frequently, such as once per epoch. Additionally, a set of constants, such as neuron types and vertex locations, may be specified, remaining unchanged during simulation. Should we create two variable tables based on the update frequency, or consider an alternative approach such as adding a string member (e.g., "constant" or "dynamical") to indicate the update behavior of each variable?"

**Comment by stiber** [comment]
This is a very good point. I was just thinking that "variables" either change or don't, but it would be good forward thinking to be more general and have one table with a tag associated with each item in the table to indicate update frequency/type. I suggest a `class enum` defined `public` within the recorder base class, rather than a `string`.

**Comment by stiber** [comment]
Right now, what I'm thinking as far as tags are:

- constant (values valid at registration and never change, so can be loaded at registration time)
- point process (values are times of events and there will be zero or more of them every epoch)
- time series (values are added to the variable every _n_ simulation ticks; there will therefore be a known and fixed number of new values each epoch)
  - Unanswered question: how to specify, hold, and record _n_?

**Comment by xiangli6** [comment]
In the new design, XmlRecorder supports variables with two unique update types:

1. Dynamical variables: Values are updated in each epoch.
2. Constant variables: Values remain unchanged during each epoch or do not need to accumulate during each epoch by the Recorder.

We have already solved the Dynamical EventBuffer variable registration. Now, we are considering other data structures in existing simulations and the recording of constant variables. XmlRecorder supports 1-D variables with three different data structures:

- EventBuffer
- VectorMatrix
- Standard Library vectors such as vector<int> or vector<BGFLOAT>.

Solutions in this issue:

1. **Adding RecordableBase Interface to VectorMatrix:**

The initial plan involves adding a new subclass/concrete class to Recordable to record constant variables, such as vertex locationsbut these variables are objects of VectorMatrix. the initial plan will disrupt the existing code in the variable owner classes. To solve this problem, we propose **adding the RecordableBase interface as the base class of VectorMatrix.**

2. **Creating RecordableVector Template:**

In addition to VectorMatrix, there are variables that use the standard library Vector, such as Vector<int>. To accommodate these variables, we suggest creating a RecordableVector template that utilizes multiple inheritance:

- **RecordableBase interface**
- **Vector template."**

**Comment by xiangli6** [comment]
Added RecordableBase Interface as the base class of matrix and created RecordableVector as the subclass of RecordableBase. 

Note about the difference between RecordableBase and EventBuffer: 

A RecordableVector is just an ordinary-appearing vector, but with the extras needed to make it Recordable (regardless of what its parent class actually is). Any class that uses it manipulates it like a vector with those additional Recordable methods (the care simulator doesn't use those extra methods, of course, so it just is used like a vector there). On the other hand, an EventBuffer has a second interface: to the Recorder classes, it looks like a RecordableVector, but to the core simulator, it looks like a buffer: it can be written to and past elements can be retrieved.
