### ISSUE TITLE
Add description of each subdirectory's use to build/README.md

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#507]
See the [build directory](https://github.com/UWB-Biocomputing/Graphitti/tree/master/build)

**Comment by stiber** [comment]
@KamathScience I am assigning this to you because there are two `.xml` files in `build/output` that are yours. Should they be tracked in the repo? There are some files under build that should be, but most not. Let's document this.

**Comment by KamathScience** [comment]
Ack, they need not be tracked in the repo, they are created as part of the unit test `SerializationTests.cpp` and `DeserializationTests.cpp`. I will go ahead and delete these.

**Comment by KamathScience** [comment]
Deleted by Xiang as part of the PR #508.
