### ISSUE TITLE
Test that all files are writeable before simulation itself starts

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#51]
Right now, the serialization file isn't opened until after the simulation runs. The same _may_ be true for the results file. We should test that it's possible to open these files for writing before the simulation runs, so that the user doesn't have to wait until after the simulation to realize that they are in the wrong working directory.

**Comment by stiber** [comment]
This should be replaced with an issue for each kind of file that is opened, which right now means a test for the recorder (data) output file and the serialization output file.

**Comment by KamathScience** [comment]
PR #261 adds result file access check before simulation.
PR #482 adds serialization file access check before simulation.
