### ISSUE TITLE
Record NG911 system performance history

### ISSUE THREAD

**Issue by jardiamj** [UWB-Biocomputing/Graphitti#538]
We need to record system performance metrics for the 911 queueing model. There are two measurements that allow us to weigh the load of the system:

- **System utilization:** The proportion of the time during the simulation that the servers are busy.
- **Time Average Queue Length:** The time-weighted average number of customers in the queue during the simulation.

These measurements can be estimated from the history of the number of busy servers at each time step, and the history of the queue length at each time step; respectively.

**Comment by stiber** [comment]
One important principle we should adhere to is to record fundamental data during simulation and defer all analysis to external code in Matlab (or, occasionally, Python). Relevant to this, the two histories are fundamental data and the two measurements are computed from that, so the histories should be recorded.

In other words, we don't put analysis code in the simulator.
