### ISSUE TITLE
Split all STDP synapse classes in two

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#54]
Right now, the STDP synapse classes combine "vanilla" STDP and a model in froemke-dan02 that takes into account sequential dependency among spike pairs. We should split these into two classes. Ideally, we should be able to use a "vanilla" method that computes individual spike pair effects for both classes (by inheritance in the case of the froemke-dan model), but then override the actual weight change operation in the latter.

**Comment by stiber** [comment]
We should replace this issue with a new one, or close it, depending on exactly what the strategy was for the 2021 implementation.

**Comment by sky1204** [comment]
We made a different weightModification function to enable us to add different implementations. We should definitely modify it depending on the direction of the lab and what our vision is for this class.
