### ISSUE TITLE
Could all the parameters in config files be included within the GraphML file?

### ISSUE THREAD

**Issue by jardiamj** [UWB-Biocomputing/Graphitti#549]
We are moving to use GraphML to feed Graphitti with predefined graphs. In addition, we have a config file that contains all the parameters associated with the simulation. The question is if we can or should include these parameters in the GraphML file as graph attributes. We need to think about the possible pros and cons of this approach.

GraphML allows the declaration of attributes under four domains: `graph`, `node`, `edge`, and `all`. See [GraphML primer](http://graphml.graphdrawing.org/primer/graphml-primer.html) for more information.

**Comment by Oelgazz** [comment]
From discussion and initial implementations, the agreed answer to this question is that all parameters that are common between all configurations (except for number of neurons) should be put in the GraphML file. This means the sections in the XML files labeled:

1. "NLIST" (Vertice Property, Already Implemented),
2. "PoolSize" (Vertice Property, Already Implemented),
3. "SimConfig" (Graph Property, TODO),
4. "RNGConfig" (Graph Property, TODO).

Should be migrated into the GraphML file.
