### ISSUE TITLE
Need additional research regarding basic STDP algorithm

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#55]
Right now, the basic STDP algorithm implemented has three flaws:

1. The change from each pair of spikes seems too large.
2. There is no upper limit on the amount of strength increase; an arbitrary hard limit is used instead.
3. There is no model for inhibitory synapses.

We need to do more research into STDP models to see how to address these shortcomings.

**Comment by stiber** [comment]
I believe this is done; just want to verify before closing.

**Comment by sky1204** [comment]
We can set a upper limit in the parameters now, but we still don't have it implemented for inhibitory neurons. Given that most models implement it just for excitatory neurons, this isn't a very major thing. I did find papers about inhibitory implementation, I'll put them in the lab drive for reference.
