### ISSUE TITLE
Merge ClusterInfo into Cluster

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#57]
ClusterInfo contains per-cluster data, rather than data global to all clusters. So, there's no need for this extra class; its contents can become part of Cluster.

## *What* is affected by this?

simulator

**Comment by stiber** [comment]
I think this is done/moot; just want someone to look at it before closing.

**Comment by christopherdokeefe** [comment]
Yeah, I don't think this is needed. ClusterInfo only exists in the old BG repo.
