### ISSUE TITLE
Fix comment in CMakeLists to indicate we are using C++17

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#598]
https://github.com/UWB-Biocomputing/Graphitti/blob/fc673110eb6d18a636ee5519e02691698c07c3c1/CMakeLists.txt#L54

**Comment by Lavinia225** [comment]
I can work on that

**Comment by stiber** [comment]
OK, please make sure to read [our contributing guide](https://github.com/UWB-Biocomputing/Graphitti/blob/fc673110eb6d18a636ee5519e02691698c07c3c1/CONTRIBUTING.md)
