### ISSUE TITLE
Assertion failure in HDF5Recorder class during large GPU simulation 

### ISSUE THREAD

**Issue by KamathScience** [UWB-Biocomputing/Graphitti#606]
The simulator encounters an assertion failure within the `compileHistories()` method of the `Hdf5GrowthRecorder` class when executing a full-size growth simulation on the GPU at epoch 33.

 This issue is seen in `version 0.9.1` of the Graphitti, whereas `version 0.9` does not display this problem.

![image](https://github.com/UWB-Biocomputing/Graphitti/assets/53545471/f6f24e6e-dd0e-449b-ba09-f2aad47ef589)

**Comment by jardiamj** [comment]
I ran this simulation and noticed that `idx2` was negative when the simulation failed. This was a wrap-around due to an overflow of the `int` data type meant to hold the value. Still, even without this, it would fail the second condition of the assertion (`idx2 < (simulator.getEpochDuration() * 100)`).

For debugging, I changed the data type to `uint64_t` and printed the value inside the `EventBuffer` and the `idx2`:
```
Current Step: 33
EventBuffer value: 18446744073709551615
idx2: 184467436076736000
```

Notice that the value inside the `EventBuffer` is the max value for the `uint64_t` data type. This must be an error, but where could it come from?

**Comment by KamathScience** [comment]
Initially, I suspected the same - that the issue might be stemming from either a loss of precision due to the conversion of `int_64` to `double`, or an integer overflow for large simulations due to our use of `idx2` as `int` instead of `int64_t`. However, upon closer examination of how `idx2` was calculated, I discovered that it was the event buffer value that was causing the simulation to trip.

I found that when `idx2` was fetching the last index of the event buffer, it would return a `uint64_t` maximum value because it never deviated from the default value set during initialization. 

```
epoch start:                                                                  19461
eventIterator - a.k.a - i : 				                       539
eventTimeSteps_.size():                                                        20001
INDEX : (epochStart_ + i) % eventTimeSteps_.size()                             20000
iVertex: 						                       687
spNeurons.vertexEvents_[iVertex][eventIterator]:                               18446744073709551615
idx2: 					                                       184467436076736000
```

This led me to suspect that the issue might be related to the circular buffer implementation in the event buffer. Upon reviewing the documentation and implementation of the event buffer, I realized that while the documentation and overall concept were sound, there was a discrepancy in how we implemented the event buffer for GPU and CPU.

On the CPU side, we increment the size of `eventTimeSteps_` by one to accommodate a slot to differentiate between a full buffer and an empty buffer:

```cpp
eventTimeSteps_(maxEvents + 1, numeric_limits<unsigned long>::max())
```

However, on the GPU side, we fail to account for this additional slot:

```cpp
int maxSpikes = vertexEvents_[0].eventTimeSteps_.size() - 1;
for (int i = 0; i < count; i++) {
    HANDLE_ERROR(cudaMemcpy(pSpikeHistory[i], vertexEvents_[i].eventTimeSteps_.data(),
                            maxSpikes * sizeof(uint64_t), cudaMemcpyHostToDevice));
}
```
As a result, when we copy over the values, the last slot remains unassigned, resulting in it retaining the `uint64_t` maximum value, which is then fetched by the recorder.

**Comment by KamathScience** [comment]
Before diving into the implementation of the fix, I want to understand the design decisions behind it. However, for now, a quick fix could be to remove the additional slot on the event buffer and utilizing `numEventsInEpoch_` to handle full and empty conditions.

```cpp
eventTimeSteps_(maxEvents, numeric_limits<unsigned long>::max())
---------
// If the buffer is full, then this is an error condition
if (numEventsInEpoch_ > 0 && (queueEnd_ == queueFront_))
```

On the GPU side, we'll use the full buffer size:

```cpp
int maxSpikes = vertexEvents_[0].eventTimeSteps_.size();
for (int i = 0; i < count; i++) {
    HANDLE_ERROR(cudaMemcpy(pSpikeHistory[i], vertexEvents_[i].eventTimeSteps_.data(),
                            maxSpikes * sizeof(uint64_t), cudaMemcpyHostToDevice));
}
```
I have successfully tested this change on the full-size growth simulation on the GPU (I manually stopped at epoch 40).

![Epoch 32 - 40](https://github.com/UWB-Biocomputing/Graphitti/assets/53545471/8deda368-fe43-4388-8450-34b28e9a19a3)
