### ISSUE TITLE
Update Documentation for Recorder (Agile Data Recording) Subsystem in Development Branch

### ISSUE THREAD

**Issue by xiangli6** [UWB-Biocomputing/Graphitti#616]
With the recent reengineering of the Recorder subsystem within the development branch, it's essential to update our documentation to reflect the changes and enhancements made to this redesigned (agile data recording) subsystem.

1) Add sequential diagram for Recorder workflow
2) Add Recorder Class Diagram
3) Update GitHub Page with Recorder Notes((Section 4.6))

**Comment by BenYang2002** [comment]
This issue is resolved by pull request #631

**Comment by BenYang2002** [comment]
This issue is resolved by pull request #631
