### ISSUE TITLE
Rename methods in AllSynapses (and subclasses) for clarity

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#65]
Method names are *ad hoc*. Let's make their names clearer, indicate if they apply to single synapses (class name implies all synapses, so no need to explicitly write that).

![uploads/baa6d1ed-3667-495c-aa58-b035dd15668e/IMG_9203.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbaa6d1ed-3667-495c-aa58-b035dd15668e%2FIMG_9203.JPG)

**Comment by stiber** [comment]
This may be done. Since we'll be working to merge the new STDP synapse code into the master branch, web can check this as that is done.

**Comment by stiber** [comment]
May already by done; need to check.

**Comment by sky1204** [comment]
I renamed some of them but not all. I think they might have been renamed during the refactoring. We can check.
