### ISSUE TITLE
Need to handle edge case in area of overlap computation

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#67]
A problem arises due to lack of precision in the computation of area of overlap, when the cosine of a chord angle is computed, erroneously, to be greater than 1. We should reorganize the computation to catch this edge case (inside the else on line 367):

```C++
BGFLOAT cosCBA = (r22 + lenAB2 - r12) / (2.0 * r2 * lenAB);
BGFLOAT cosCAB = (r12 + lenAB2 - r22) / (2.0 * r1 * lenAB);
if (fabs(cosCBA) >= 1.0 || fabs(cosCAB) >= 1.0) {
   (*area)(i, j) = 0.0;
} else {
// The rest of the existing computation goes here
```

https://github.com/UWB-Biocomputing/BrainGrid/blob/90cac03e8c1ab4472aacc40ab05962c9334fa2ae/Connections/ConnGrowth.cpp#L368-L381

**Comment by VivekGandhi54** [comment]
@jbrown725 Does 870af82f84f7728003fa3ec1a9d55844cd16a91c close this too?
I'm pretty sure the bug is fixed.

**Comment by jbrown725** [comment]
The implementation doc with those images has been added. It does look like the bug fix is also added, so I'll close this.
