### ISSUE TITLE
Bring code up to C++11 standard

### ISSUE THREAD

**Issue by stiber** [UWB-Biocomputing/Graphitti#76]
See issue UWB-Biocomputing/BrainGrid#232 to see the bug aspect of this. Currently, the Makefile is set to compile code using the C++98 standard. There is a problem with initialization of static const member variables, however. Also, generally, there can be some code cleanup and modernization (that might also have a small positive impact on performance). This is a worthwhile project.

## *What* is affected by this?

Simulator

**Comment by torisalvatore** [comment]
Can we close this issue?

**Comment by stiber** [comment]
Good question. There is still the `nullptr` issue, though that may be resolved soon. We should change all of our compile-time constants to `constexpr`. There may be other things. This is another one of those "need to go through the code and fix minor problems everywhere" issues. I've labeled it a good first issue because it requires only limited knowledge of the codebase.
